# Generated by Django 6.0.4 on 2026-04-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user_name',
            new_name='customer_name',
        ),
    ]
