# Generated by Django 6.0.4 on 2026-04-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_rename_user_name_complaint_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='priorty',
            new_name='priority',
        ),
    ]
